name: Android CI

on:
  push:
    branches: [ main, "release/**", "hotfix/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (assembleDebug)
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK/NDK components
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "cmake;3.22.1" \
            "ndk;27.1.12297006"

      - name: Configure Gradle permissions
        run: chmod +x ./gradlew

      - name: Gradle version
        run: ./gradlew --version

      - name: Assemble Debug
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon

      - name: Run unit tests
        run: ./gradlew test --stacktrace --no-daemon

      - name: Upload debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

  release:
    name: Assemble Release (signed)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: build
    if: |
      github.event_name == 'push' && 
      (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) && 
      secrets.ANDROID_KEYSTORE_BASE64 != '' && 
      secrets.ANDROID_KEYSTORE_PASSWORD != '' && 
      secrets.ANDROID_KEY_ALIAS != '' && 
      secrets.ANDROID_KEY_ALIAS_PASSWORD != ''

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK/NDK components
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "cmake;3.22.1" \
            "ndk;27.1.12297006"

      - name: Configure Gradle permissions
        run: chmod +x ./gradlew

      - name: Restore keystore from secrets
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          mkdir -p $HOME/.android
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > $HOME/.android/release.jks

      - name: Assemble Release (with signing)
        env:
          ANDROID_KEYSTORE: ${{ runner.temp }}/release.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
        run: |
          # Use keystore from HOME to avoid path spaces issues
          cp $HOME/.android/release.jks $ANDROID_KEYSTORE
          ./gradlew :app:assembleRelease \
            -Pandroid.injected.signing.store.file=$ANDROID_KEYSTORE \
            -Pandroid.injected.signing.store.password=$ANDROID_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$ANDROID_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$ANDROID_KEY_ALIAS_PASSWORD \
            --stacktrace --no-daemon

      - name: Upload release APK/AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-artifacts
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
